[project]
name = "steel-quality-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "geopandas>=1.0.1",
    "imbalanced-learn>=0.13.0",
    "jupyter>=1.1.1",
    "marimo>=0.13.11",
    "matplotlib>=3.10.3",
    "numpy<2.2",
    "polars>=1.29.0",
    "pyarrow>=20.0.0",
    "scikit-learn>=1.6.1",
    "scikit-optimize>=0.10.2",
    "seaborn>=0.13.2",
    "tensorflow==2.15.1",
    "xgboost>=3.0.2",
]
